version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "daily"
